In [2]:
import torch
x = torch.tensor(5)
x

tensor(5)

In [3]:
x.shape

torch.Size([])

In [4]:
x = torch.tensor([2,4,6,8])
x

tensor([2, 4, 6, 8])

In [5]:
x.shape

torch.Size([4])

In [6]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
x.shape

torch.Size([2, 3])

In [8]:
x = torch.tensor([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

In [9]:
x

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [10]:
x.shape

torch.Size([2, 2, 2])

In [11]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [12]:
x.shape

torch.Size([3])

In [13]:
x = torch.zeros(3,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
x = torch.rand(3,3)
x

tensor([[0.8611, 0.5734, 0.8572],
        [0.4021, 0.7601, 0.2045],
        [0.6212, 0.7762, 0.6971]])

In [16]:
x = torch.tensor([1,2,3])

x.dtype

torch.int64

In [17]:
x = torch.tensor([1.0,2.0,3.0])
x.dtype

torch.float32

In [18]:
x = torch.tensor([1,2,3], dtype=torch.float32)
x.dtype

torch.float32

In [19]:
x

tensor([1., 2., 3.])

In [20]:
a = torch.tensor([2,4])

b = torch.tensor([1,3])

a+b

tensor([3, 7])

In [21]:
a*b

tensor([ 2, 12])

In [22]:
A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([
    [5,6],
    [7,8]
])

torch.matmul(A,B)

tensor([[19, 22],
        [43, 50]])

In [23]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [26]:
x = x.cpu()

In [27]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward()
x.grad

tensor(4.)

In [28]:
y

tensor(4., grad_fn=<PowBackward0>)

In [29]:
x

tensor(2., requires_grad=True)

In [31]:
x = torch.tensor(2.0, requires_grad=True)
y = x * 3
z = y + 5

In [32]:
z.backward()

In [33]:
x.grad

tensor(3.)

In [35]:
y.detach()

tensor(6.)

In [36]:
x

tensor(2., requires_grad=True)

In [37]:
y

tensor(6., grad_fn=<MulBackward0>)

In [38]:
z

tensor(11., grad_fn=<AddBackward0>)

In [39]:
x.grad

tensor(3.)

In [40]:
import numpy as np
arr = np.array([1,2,3])
tensor = torch.from_numpy(arr)

In [41]:
array = tensor.numpy()